apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 4000
volumes:
    - name: strg_logs
      persistentVolumeClaim:
        claimName: myclaim

kind: Deployment
metadata:
  name: koa-deployment
  labels:
    app: koa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: koa
  template:
    metadata:
      labels:
        app: koa
    spec:
      containers:
      - name: koa
        image: veracity:1.2
        ports:
        - containerPort: 3000
volumes:
    - name: strg_logs
      persistentVolumeClaim:
        claimName: myclaim

kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
kind: PersistentVolume
metadata:
  name: strg_logs
spec:
  storageClassName: ""
  claimRef:
    name: strg_logs
    namespace: foo
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi