apiVersion: apps/v1

kind: Deployment

metadata:

  name: koa-deployment

  labels:

    app: koa

spec:

  replicas: 3

  selector:

    matchLabels:

      app: koa

  template:

    metadata:

      labels:

        app: koa

    spec:

      containers:

      - name: koa

        image: veracity:1.2

        ports:

        - containerPort: 3000
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000